server:
  port: 80
spring:
  application:
    name: cloud-consumer-order



eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息，默认为true，单节点无所谓。集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 集群版注册中心
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      # 单机版注册中心
      #defaultZone: http://localhost:7001/eureka
  #服务名称完善和ip显示
  instance:
    instance-id: order80
    prefer-ip-address: true
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.sercice.PaymentFeignService: debug

