server:
  port: 9527
spring:
  application:
    name: cloud-getway9527
  cloud:
    gateway:
      enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-eureka-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-eureka-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式


eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息，默认为true，单节点无所谓。集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 集群版注册中心
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      # 单机版注册中心
      #defaultZone: http://localhost:7001/eureka
  #服务名称完善和ip显示
  instance:
    instance-id: cloud-getway9527
    prefer-ip-address: true
    #Eureka客服端向服务端发送心跳的时间间隔，默认是30秒
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次收到心跳后等待时间上限，默认是90秒，超时移除服务
    #lease-expiration-duration-in-seconds: 2
